### ISSUE TITLE
Running according to the installation procedure will fail with npm run app

### ISSUE THREAD

**Issue by nosix** [benishouga/sourcer#1]
`npm run app` を実行したときに、out/main/server/index.js が見つからないとエラーになります。

また、`node_modules/.bin/tsc` を実行して index.js を生成した場合には out/main/server/index.html が見つからないとエラーになります。

**Comment by benishouga** [comment]
報告ありがとうございます。
12f785fd7478af371f788db824151158c34c3ace で修正しました。

```
git clone https://github.com/benishouga/sourcer.git
cd sourcer
npm install
npm start
```
が正しかったです。
